### ISSUE TITLE
can't open .crx

### ISSUE THREAD

**Issue by cnelson45** [SAP/digitalboardroom-multidesktop-fullscreen-chrome#1]
Hi There,

I have windows 10 but not a touch display pc. I am trying to install the crx, but when I click on it, it asks me for a program to run it, which I do not have. Any ideas which program I need to install the .crx? thanks!

**Comment by vamsiraju** [comment]
You can open the .crx file using Chrome. More instructions are here, https://github.com/SAP/digitalboardroom-multidesktop-fullscreen-chrome#install-the-chrome-app
