### ISSUE TITLE
F11 issue

### ISSUE THREAD

**Issue by reducto1987** [SAP/digitalboardroom-multidesktop-fullscreen-chrome#2]
Hi, 

Once the extension is in full screen mode and do some interaction in the digital boardroom we can no longer exit full screen mode by pressing f11. Kindly fix it.

Requirement is that we need to switch between demos infront of customers and it is a cumbersome process to close the extension and then open the other demo again.

Thanks.

Ahmed Hassan,
SAP.

**Comment by twpenner** [comment]
Hi Ahmed,
This issue is now fixed in the 0.4 version.
- Terry
